# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OutdoorTribe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OutdoorTribe

pod 'FirebaseFirestore'
pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'SwiftLint'
pod 'Kingfisher', '~> 7.0'
pod 'FirebaseFirestoreSwift'
pod 'Cosmos', '~> 23.0'
pod 'GoogleWebRTC', '~> 1.1'
pod 'IQKeyboardManagerSwift'
end
